pose1 : [0.335203,-0.339902,0.861295,110.841,64.795,-36.610]
pose2 : [0.365914,-0.259104,0.896019,144.104,74.541,-22.717]
pose3 : [0.307356,-0.3184,1.024783,-106.586,63.25,105.538]
pose4 : [0.299652,-0.340230,0.943300,176.175,85.632,34.512]
pose5 : [0.303078,-0.337831,0.888769,176.175,85.63,34.512]
pose6 : [0.327.845,-0.31788,0.946,176.172,85.630,34.511]
