kesai : [2.0,3.0,2.0,2.0,1.5,1.5,1.5]
M: [15, 10, 7.5, 7.5, 4.0, 3.0, 1.5]
K: [1, 1, 1, 1, 1, 1, 1]
F_joint_stop : [3.0, 5.0, 3.0, 3.0, 1.5, 1.0, 0.5]
a_sensor : [140.6, 140.6, 89.05, 90.19, 85.41, 42.72, 42.72]
b_sensor: [-6.316, -6.316, -1.958, -1.743, -2.592, -0.8113, -0.8113]
joint_K: [0.8, 0.6, 0.9, 0.8, 0.9, 1.0, 1.2]
ZeroOffset : [-0.9732, -1.71, 0.35952, 1.3,-0.22874, 0.60468, 0.64118]

# 碰撞检测
flag_collision_detection: false
joint_collisions: [4,15,7,12,4,4,2]
# mass : 2.413
mass : 0
mass_center : [0.0000,0,0]
